dress/dress/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('dressapp.urls'))
]

if settings.DEBUG:
     urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
     urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dress/dressapp/urls.py
from django.urls import path
from . import views
app_name='dressapp'
urlpatterns = [

    path('',views.dress,name='dress'),
    path('dress/<int:dress_id>/',views.product,name='product'),
    path('add/',views.add_dress,name='add_dress'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

dress/dressapp/models.py
from django.db import models

# Create your models here.
class Dress(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    price=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

dress/dressapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Dress
from . form import DressForm

# Create your views here.
def dress(request):
    iteam=Dress.objects.all()
    context={
        'dress_list':iteam
    }
    return render(request,'iteam.html',context)
def product(request,dress_id):
    dress=Dress.objects.get(id=dress_id)
    return render (request,"detail.html",{'dress':dress})
    # return HttpResponse("this dress no is %s" % dress_id)

def add_dress(request):
    if request.method=="POST":
        name = request.POST.get('name',)
        desc = request.POST.get('desc',)
        price = request.POST.get('price',)
        image = request.FILES['img']
        dress = Dress(name=name,desc=desc,price=price,img=image)
        dress.save()
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    dress=Dress.objects.get(id=id)
    form=DressForm(request.POST or None, request.FILES, instance=dress)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'dress':dress})

def delete(request,id):
    if request.method == "POST":
        dress=Dress.objects.get(id=id)
        dress.delete()
        return redirect('/')
    return render(request,'delete.html')

dress/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method = "POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="ENTER DRESS NAME"><br>
    <input type="text" name="desc" placeholder="DESCRIPTION"><br>
    <input type="text" name="price" placeholder="ENTER PRICE"><br>
    <input type="file" name="img" ><br>
    <input type="submit">
</form>

{% endblock %}

dress/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dress</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">DRESS LAND</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dressapp:add_dress' %}" class="btn btn-primary">ADD</a>
      </li>
    </ul>
    <span class="navbar-text">
      Online Dress
    </span>
      <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

dress/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you want to delete this file?
    <input type="submit">
</form>

dress/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{dress.img.url}}" width="400" height="550">
                </div>
                    <div class="col-md-6">
                        <h1>{{dress.name}}</h1><br>
                        <h6>{{dress.desc}}</h6><br>
                        <h1>{{dress.price}}</h1><br>
                <a class="btn btn-warning" href="{% url 'dressapp:update' dress.id%}">update</a>
            <a class="btn btn-danger" href="{% url 'dressapp:delete' dress.id%}">delete</a>
        </div>
    </div>
</div>
{% endblock %}

dress/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">

dress/templates/iteam.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {%for i in dress_list %}
            <div class="col-md-3">
                <div class="card" style= "width":100 "height":250>
                    <img src="{{i.img.url}}" class="card-img-top" alt="..." width="5" height="300">
                <div class="card-body">
             <div { column-gap: 40px; }>
        <h5 class="card-title">{{i.name}}</h5>
    <a href="{% url 'dressapp:product' i.id %}" class="btn btn-primary">view Details>></a><br>
 </div>
</div>
</div>
</div>
        {% endfor %}
</div>
</div>

{% endblock %}